### PR TITLE
[work in progress] adds pricing table

### PR DESCRIPTION
**Pull request by ampatspell**

### CODE REVIEW

**Comment by ampatspell** [comment]
@eugenoprea, @relu, which API endpoing should I query for pricing info?

**Comment by ampatspell** [comment]
screen shot 2017-07-06 at 19 35 06

**Comment by relu** [comment]
@ampatspell `https://s-api.elevatrapp.com/api/v1/plans` for staging and `https://api.elevatrapp.com/api/v1/plans` for prod.

**Comment by ampatspell** [comment]
which plans will be "most-popular"?

**Comment by ampatspell** [comment]
also, production API returns 12 plans for montly and yearly. which ones should I show?

**Comment by eugenoprea** [comment]
Just to confirm, the third plan should be most popular.

Also, the first three should show the lowest prices and the fourth one should show an input so that people can add the number of contacts.

**Comment by relu** [comment]
Gonna merge what you have so far here into master, will not delete your branch so please open a separate PR if necessary.

**Pull request merged**
